//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursavaa
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPoint
    {
        public int IdPoint { get; set; }
        public string PointName { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int HousNumber { get; set; }
        public string StreetName { get; set; }
        public string GityName { get; set; }
    }
}
