//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursavaa
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProduct
    {
        public int IdZakaz { get; set; }
        public string ProduktName { get; set; }
        public int Cost { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string PointName { get; set; }
        public string StatusName { get; set; }
    }
}
