//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursavaa
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewStaff
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string LastName { get; set; }
        public int age { get; set; }
        public int ENNNum { get; set; }
        public string GenderName { get; set; }
        public string UnitCodeName { get; set; }
        public string MaritalStatusName { get; set; }
    }
}
