//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursavaa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int IdZakaz { get; set; }
        public int IdProdukt { get; set; }
        public int IdPoint { get; set; }
        public int IdStatus { get; set; }
        public int IdUser { get; set; }
    
        public virtual Point Point { get; set; }
        public virtual Produkt Produkt { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
